/* GENERATED by scripts/gen-deck-index.mjs — do not edit by hand. */
window.registerDeck({
  "schemaVersion": 1,
  "id": "world-history-first-timeline",
  "name": "World History: A First Timeline",
  "blurb": "The human story in forty moments, from the first Australians to Mandela.",
  "emoji": "🌍",
  "tier": "free",
  "filters": [
    {
      "id": "era",
      "label": "By Era",
      "multi": true,
      "options": [
        {
          "value": "prehistory",
          "label": "Prehistory (to c.3000 BCE)"
        },
        {
          "value": "ancient",
          "label": "Ancient (to c.450)"
        },
        {
          "value": "medieval",
          "label": "Medieval (c.450–1500)"
        },
        {
          "value": "early-modern",
          "label": "Early Modern (c.1500–1760)"
        },
        {
          "value": "industrial",
          "label": "Industrial (c.1760–1970)"
        },
        {
          "value": "modern",
          "label": "Modern (1970–present)"
        }
      ],
      "get": {
        "strategy": "eraBucket"
      }
    },
    {
      "id": "continent",
      "label": "By Continent",
      "multi": true,
      "options": [
        {
          "value": "africa",
          "label": "Africa"
        },
        {
          "value": "asia",
          "label": "Asia"
        },
        {
          "value": "europe",
          "label": "Europe"
        },
        {
          "value": "americas",
          "label": "Americas"
        },
        {
          "value": "middle-east",
          "label": "Middle East"
        },
        {
          "value": "oceania",
          "label": "Oceania"
        },
        {
          "value": "global",
          "label": "Global"
        }
      ],
      "get": {
        "field": "continent"
      }
    },
    {
      "id": "theme",
      "label": "By Theme",
      "multi": true,
      "options": [
        {
          "value": "governance",
          "label": "Governance & Rights"
        },
        {
          "value": "empire",
          "label": "Empires & Civilisations"
        },
        {
          "value": "war-peace",
          "label": "War & Peace"
        },
        {
          "value": "religion",
          "label": "Religion & Belief"
        },
        {
          "value": "ideas",
          "label": "Ideas & Learning"
        },
        {
          "value": "society",
          "label": "Society & Daily Life"
        },
        {
          "value": "exploration",
          "label": "Exploration & Contact"
        }
      ],
      "get": {
        "field": "category"
      }
    }
  ],
  "events": [
    {
      "id": "first-peoples-australia",
      "title": "First Peoples Reach Australia",
      "year": -65000,
      "circa": true,
      "yearEnd": -53000,
      "era": "prehistory",
      "category": "society",
      "continent": "oceania",
      "emoji": "🛶",
      "who": "Aboriginal Australian ancestors",
      "where": "Australia",
      "why": "Earliest known human settlement of the continent.",
      "fact": "Sea levels were far lower, so people walked and paddled into a landmass joined to New Guinea.",
      "summary": "Tens of thousands of years ago, people crossed from Southeast Asia into Australia. At that time the sea was much lower, joining Australia to New Guinea in one huge landmass. These travellers were the ancestors of today's Aboriginal Australians, whose cultures have continued on the continent ever since. Their voyage was among the earliest sea crossings people ever made.",
      "lat": -25,
      "lng": 134,
      "area": 2600
    },
    {
      "id": "first-farming",
      "title": "First Farming Begins",
      "year": -9500,
      "circa": true,
      "yearEnd": -8500,
      "era": "prehistory",
      "category": "society",
      "continent": "middle-east",
      "emoji": "🌾",
      "who": "Early farmers of the Fertile Crescent",
      "where": "Southwest Asia",
      "why": "People began planting and herding instead of foraging.",
      "fact": "In the Levant, people sowed wild wheat and barley, then stayed put to harvest and store the grain.",
      "summary": "About eleven thousand years ago, people in the Fertile Crescent began planting seeds and herding animals instead of only hunting and gathering. Farming produced more food than foraging, so villages grew and some people took up new crafts. This shift, often called the Neolithic Revolution, spread slowly to other regions and eventually changed how most humans lived.",
      "lat": 33,
      "lng": 36,
      "area": 700,
      "connections": [
        {
          "to": "egypt-unifies",
          "type": "contributing",
          "rationale": "Farming produced storable surpluses, and stored food is what lets a valley feed rulers, scribes and soldiers who do not grow their own. Egypt's unification rests on managed Nile agriculture."
        },
        {
          "to": "great-pyramid",
          "type": "contributing",
          "rationale": "A workforce building at Giza has to be fed from something other than its own fields; the agricultural surplus is the precondition."
        }
      ]
    },
    {
      "id": "egypt-unifies",
      "title": "Egypt Unifies Under One Pharaoh",
      "year": -3100,
      "circa": true,
      "yearEnd": -3000,
      "category": "empire",
      "continent": "africa",
      "emoji": "👑",
      "who": "Narmer and early Egyptian kings",
      "where": "Nile Valley, Egypt",
      "why": "Joined Upper and Lower Egypt into one kingdom.",
      "fact": "Rulers from the south conquered the Nile Delta, and the crown became a double crown of two lands.",
      "summary": "Ancient Egypt had long been two lands: the narrow valley of Upper Egypt and the wide delta of Lower Egypt. Around 3100 BCE a powerful ruler from the south conquered the north and wore a double crown. One king now commanded the whole Nile, its farms and its trade. This unity let Egyptian civilisation flourish for thousands of years.",
      "lat": 26,
      "lng": 31,
      "area": 800,
      "connections": [
        {
          "to": "great-pyramid",
          "type": "necessary",
          "rationale": "A pyramid is a state project: it needs a unified kingdom able to levy labour and move stone. Without the pharaonic state there is no Giza."
        }
      ]
    },
    {
      "id": "great-pyramid",
      "title": "Great Pyramid Completed at Giza",
      "year": -2560,
      "circa": true,
      "category": "society",
      "continent": "africa",
      "emoji": "🔺",
      "who": "Workers for Pharaoh Khufu",
      "where": "Giza, Egypt",
      "why": "Tomb of Khufu; tallest building for millennia.",
      "fact": "More than two million stone blocks were hauled into place, and it stayed the tallest building for thousands of years.",
      "summary": "The Great Pyramid at Giza was built as a tomb for the pharaoh Khufu. Workers moved more than two million blocks of stone, some weighing many tonnes, into a shape that has lasted over four thousand years. It was the tallest building in the world for thousands of years. For the Egyptians, it was a stairway to the gods.",
      "lat": 29.98,
      "lng": 31.13,
      "area": 30
    },
    {
      "id": "confucius",
      "title": "Confucius Teaches in China",
      "year": -551,
      "circa": true,
      "category": "ideas",
      "continent": "asia",
      "emoji": "📚",
      "who": "Confucius (Kong Qiu)",
      "where": "Lu state, China",
      "why": "His ethical teaching shaped East Asian thought.",
      "fact": "He gathered students and taught that good government begins with virtue, a teaching later collected in the Analects.",
      "summary": "Confucius lived during a time of warring states in China. He travelled and taught that rulers should govern by example and treat people with kindness. After his death, his students collected his sayings in a book called the Analects. For more than two thousand years his ideas shaped education and government across East Asia.",
      "lat": 35.6,
      "lng": 116.9,
      "area": 400,
      "connections": [
        {
          "to": "qin-unifies-china",
          "type": "contributing",
          "rationale": "Confucius gave China a shared vocabulary of rule - the trained official, the moral example, the unified order - that the imperial state later claimed to embody."
        }
      ]
    },
    {
      "id": "athenian-democracy",
      "title": "Cleisthenes Establishes Athenian Democracy",
      "year": -508,
      "category": "governance",
      "continent": "europe",
      "emoji": "🗳️",
      "who": "Cleisthenes of Athens",
      "where": "Athens, Greece",
      "why": "Citizens gained a direct voice in governing.",
      "fact": "He reorganised Athens into new tribal groups so that ordinary citizens, not noble families, chose the council.",
      "summary": "Before Cleisthenes, Athens was run by a few wealthy families. He reorganised the citizens into new groups and gave an assembly of ordinary men the power to debate and vote on laws. Not everyone could take part — women, enslaved people and foreigners were excluded. Still, the idea of citizens ruling themselves became one of Athens' greatest exports.",
      "lat": 37.98,
      "lng": 23.73,
      "area": 200,
      "connections": [
        {
          "to": "plato-academy",
          "type": "contributing",
          "rationale": "The Academy grows out of the Athenian polis and its argument culture; Plato's dialogues are set in and argue about the democracy Cleisthenes founded."
        }
      ]
    },
    {
      "id": "buddha-monastic-order",
      "title": "The Buddha Founds the Monastic Order",
      "year": -400,
      "circa": true,
      "category": "religion",
      "continent": "asia",
      "emoji": "☸️",
      "who": "Siddhartha Gautama, the Buddha",
      "where": "Northern India",
      "why": "Founded a community of monks and nuns.",
      "fact": "Buddhists hold that he taught a middle path between luxury and hardship, and his followers gave up possessions to seek release from suffering.",
      "summary": "Siddhartha Gautama was a prince who left his palace to seek an end to suffering. Around 400 BCE, after years of searching, he became the Buddha, or 'awakened one'. He founded a community of monks and nuns who gave up possessions to follow his teaching. Buddhists believe his teaching offered a path to freedom from suffering that others could follow too.",
      "lat": 24.7,
      "lng": 84.99,
      "area": 500
    },
    {
      "id": "plato-academy",
      "title": "Plato Founds the Academy",
      "year": -387,
      "circa": true,
      "yearEnd": -383,
      "category": "ideas",
      "continent": "europe",
      "emoji": "🎓",
      "who": "Plato, student of Socrates",
      "where": "Athens, Greece",
      "why": "A school for philosophy, maths and politics.",
      "fact": "His school met in a grove outside the city walls and lasted for centuries, teaching mathematics alongside philosophy.",
      "summary": "Plato was a student of Socrates and one of the first thinkers to write philosophy down as lasting books. Around 387 BCE he founded a school called the Academy near Athens, where students studied mathematics, astronomy and politics. It is often called the first university in the western world, and it lasted for centuries.",
      "lat": 37.99,
      "lng": 23.71,
      "area": 150,
      "connections": [
        {
          "to": "alexander-dies",
          "type": "contributing",
          "rationale": "Alexander was tutored by Aristotle, a product of Plato's school, so the Academy's project of educating rulers reached its most famous pupil."
        }
      ]
    },
    {
      "id": "alexander-dies",
      "title": "Alexander the Great Dies at Babylon",
      "year": -323,
      "category": "empire",
      "continent": "europe",
      "emoji": "⚔️",
      "who": "Alexander III of Macedon",
      "where": "Babylon, Mesopotamia",
      "why": "His empire was divided among his generals.",
      "fact": "His Macedonian generals carved the empire into separate kingdoms, and he died before reaching his mid-thirties.",
      "summary": "Alexander of Macedon became king as a young man and never lost a battle. In just over a decade he conquered an empire reaching from Greece to India. He died at Babylon in 323 BCE, before he turned thirty-three. Because he left no strong heir, his generals divided the empire among themselves, beginning the Hellenistic age.",
      "lat": 32.54,
      "lng": 44.42,
      "area": 400,
      "connections": [
        {
          "to": "augustus-principate",
          "type": "contributing",
          "rationale": "Augustus's Rome is the power that absorbs the Hellenistic kingdoms; Cleopatra and Antony are the last of Alexander's successor states."
        }
      ]
    },
    {
      "id": "qin-unifies-china",
      "title": "Qin Unifies China",
      "year": -221,
      "category": "empire",
      "continent": "asia",
      "emoji": "🐉",
      "who": "Qin Shi Huang",
      "where": "China",
      "why": "First emperor; standardised script, money and roads.",
      "fact": "The first emperor standardised writing, coinage and axle widths, and joined older walls into a northern defence.",
      "summary": "For centuries China was divided into competing states. The state of Qin defeated its rivals and, in 221 BCE, its king declared himself the First Emperor. He standardised writing, weights, money and the width of cart axles. He also connected older walls into a long northern defence. His dynasty was short, but the empire he created lasted far longer.",
      "lat": 34.34,
      "lng": 108.71,
      "area": 1500
    },
    {
      "id": "augustus-principate",
      "title": "Augustus Establishes the Roman Principate",
      "year": -27,
      "category": "empire",
      "continent": "europe",
      "emoji": "🏛️",
      "who": "Octavian, later called Augustus",
      "where": "Rome",
      "why": "Began the Roman Empire under one ruler.",
      "fact": "He kept republican titles while holding the army and treasury, so Rome looked like a republic but was ruled by one man.",
      "summary": "After the assassination of Julius Caesar, his heir Octavian fought his way to sole power. In 27 BCE the Senate gave him the name Augustus. He kept the old republican offices but controlled the army and the money. Rome still looked like a republic, yet one man now decided almost everything — the arrangement we call the Roman Empire.",
      "lat": 41.9,
      "lng": 12.5,
      "area": 1200,
      "connections": [
        {
          "to": "birth-of-jesus",
          "type": "contributing",
          "rationale": "Jesus is born a Roman provincial subject; the census and the governor in the Gospels are instruments of the Augustan order."
        },
        {
          "to": "fall-western-rome",
          "type": "contributing",
          "rationale": "The imperial system Augustus built is the thing that eventually falls; its later crises are the story of the fall."
        }
      ]
    },
    {
      "id": "birth-of-jesus",
      "title": "Birth of Jesus",
      "year": -5,
      "circa": true,
      "yearEnd": -4,
      "category": "religion",
      "continent": "middle-east",
      "emoji": "🌟",
      "who": "Jesus of Nazareth",
      "where": "Judaea, Roman province",
      "why": "Central figure of Christianity.",
      "fact": "Christians believe he was born in Bethlehem, and the calendar later placed his birth a few years off.",
      "summary": "Jesus was born in the Roman province of Judaea around the end of the first century BCE. Christians believe he was the son of God and was born in Bethlehem. His life and teaching became the centre of Christianity, today the world's largest religion. The calendar we use was later designed to count years from his birth, though the monk who calculated it was a few years off.",
      "lat": 31.7,
      "lng": 35.2,
      "area": 200,
      "connections": [
        {
          "to": "hijra",
          "type": "contributing",
          "rationale": "Islam emerges from the monotheism of Israel; Muhammad's community sees itself as the continuation of Abraham's line."
        }
      ]
    },
    {
      "id": "fall-western-rome",
      "title": "Odoacer Deposes the Last Western Roman Emperor",
      "year": 476,
      "category": "war-peace",
      "continent": "europe",
      "emoji": "🏰",
      "who": "Odoacer; Emperor Romulus Augustulus",
      "where": "Ravenna, Italy",
      "why": "Ended the Western Roman Empire.",
      "fact": "The boy emperor was sent into retirement, and the eastern emperor in Constantinople still claimed to rule the whole empire.",
      "summary": "For centuries the Roman Empire had been governed from both Rome and Constantinople. In 476 the general Odoacer removed Romulus Augustulus, the last emperor in the west. The boy was sent into retirement and Odoacer ruled Italy himself. Historians treat this as the end of the Western Roman Empire, though the eastern half survived for another thousand years.",
      "lat": 44.42,
      "lng": 12.2,
      "area": 300,
      "connections": [
        {
          "to": "charlemagne",
          "type": "contributing",
          "rationale": "Charlemagne's empire presents itself as the restoration of the western Roman order, and the pope crowns him emperor of the Romans."
        },
        {
          "to": "constantinople-falls",
          "type": "echo",
          "rationale": "The eastern empire survived the west by a thousand years and then fell the same way - a capital lost to besiegers. 1453 is the same event, deferred."
        }
      ]
    },
    {
      "id": "hijra",
      "title": "The Hijra: Muhammad Founds the Muslim Community",
      "year": 622,
      "category": "religion",
      "continent": "middle-east",
      "emoji": "🕌",
      "who": "Muhammad and early Muslims",
      "where": "Mecca to Medina, Arabia",
      "why": "Start of the Muslim calendar.",
      "fact": "Muslims believe he left Mecca for Medina, where the community grew into a lasting religious and political body.",
      "summary": "In 622 CE, Muhammad and his followers left Mecca for the city of Medina. This journey is called the Hijra. In Medina the small community of Muslims grew into a religious and political community with its own laws. Muslims count the years of their calendar from this event, which marks the start of the Islamic era.",
      "lat": 24.47,
      "lng": 39.61,
      "area": 400,
      "connections": [
        {
          "to": "mansa-musa",
          "type": "contributing",
          "rationale": "Mansa Musa's pilgrimage is a journey inside the Muslim world the hijra founded; his gold and his fame travel on its pilgrimage and trade routes."
        }
      ]
    },
    {
      "id": "charlemagne",
      "title": "Charlemagne Crowned Emperor",
      "year": 800,
      "category": "governance",
      "continent": "europe",
      "emoji": "👑",
      "who": "Charlemagne; Pope Leo III",
      "where": "Rome",
      "why": "Revived the idea of a western empire.",
      "fact": "The pope placed the crown on his head during a Christmas service, tying the new empire closely to the church.",
      "summary": "Charlemagne, king of the Franks, built an empire covering much of western Europe. On Christmas Day in the year 800, Pope Leo III crowned him emperor in Rome. The ceremony revived the idea of a western empire and tied the new ruler closely to the church. It also planted a lasting argument about who truly held power in Europe.",
      "lat": 41.9,
      "lng": 12.5,
      "area": 800
    },
    {
      "id": "battle-hastings",
      "title": "Battle of Hastings",
      "year": 1066,
      "category": "war-peace",
      "continent": "europe",
      "emoji": "⚔️",
      "who": "William of Normandy; Harold Godwinson",
      "where": "Senlac Hill, England",
      "why": "Norman victory changed English rule and language.",
      "fact": "Harold was killed, say the sources, by an arrow, and William marched to London to be crowned that winter.",
      "summary": "In 1066, William of Normandy claimed the English throne, but Harold Godwinson had already been crowned king. Their armies met near Hastings, and Harold was killed in the fighting. William marched to London and was crowned that winter. Norman rule changed English law, land ownership and language, adding thousands of French words to English.",
      "lat": 50.91,
      "lng": 0.49,
      "area": 60,
      "connections": [
        {
          "to": "magna-carta-first",
          "type": "contributing",
          "rationale": "Magna Carta is a baronial reaction to the strong Norman monarchy Hastings established."
        }
      ]
    },
    {
      "id": "genghis-khan",
      "title": "Genghis Khan Proclaimed Universal Ruler",
      "year": 1206,
      "category": "empire",
      "continent": "asia",
      "emoji": "🏹",
      "who": "Temujin, later Genghis Khan",
      "where": "Steppe of Mongolia",
      "why": "United Mongol tribes into a war machine.",
      "fact": "A gathering of steppe chiefs gave him the title, and Mongol armies built the largest land empire in history.",
      "summary": "In 1206, a gathering of Mongol chiefs proclaimed Temujin their universal ruler, giving him the title Genghis Khan. He organised the tribes into a disciplined army and set out to conquer. His successors built the largest land empire in history, stretching from China to eastern Europe. The Mongols also reopened trade routes linking distant civilisations.",
      "lat": 47.9,
      "lng": 106.9,
      "area": 2000,
      "connections": [
        {
          "to": "babur-mughal",
          "type": "contributing",
          "rationale": "Babur claimed descent from Genghis Khan and Timur, and the dynasty he founded named itself Mongol."
        }
      ]
    },
    {
      "id": "magna-carta-first",
      "title": "King John Seals Magna Carta",
      "year": 1215,
      "category": "governance",
      "continent": "europe",
      "emoji": "📜",
      "who": "King John; rebel barons",
      "where": "Runnymede, England",
      "why": "Placed the king under the law.",
      "fact": "Rebel barons forced King John to accept that free men could not be imprisoned without lawful judgment.",
      "summary": "Magna Carta was a peace agreement forced on King John by rebel barons. It said that the king had to obey the law and that free men could not be imprisoned without a lawful trial. Most of its clauses dealt with taxes and land, and the pope soon cancelled it. Yet its promise of limited government was remembered and reused for centuries.",
      "lat": 51.44,
      "lng": -0.56,
      "area": 60,
      "connections": [
        {
          "to": "american-revolution",
          "type": "contributing",
          "rationale": "Magna Carta is the precedent the American colonists cite for the principle that the king is himself under law."
        }
      ]
    },
    {
      "id": "polynesians-aotearoa",
      "title": "Polynesians Settle Aotearoa",
      "year": 1280,
      "circa": true,
      "yearEnd": 1300,
      "category": "society",
      "continent": "oceania",
      "emoji": "🛶",
      "who": "Polynesian voyagers",
      "where": "Aotearoa (New Zealand)",
      "why": "One of the last great ocean migrations.",
      "fact": "Navigators read stars and swells and birds to cross open ocean, then settled a land with no people and few land mammals.",
      "summary": "Polynesian voyagers were among the greatest navigators in history. Sailing in large canoes, they read the stars, ocean swells and birds to find distant islands. Around 1280 they reached Aotearoa, now New Zealand, and settled it. The land had no people and few land mammals, so the settlers adapted their farming and hunting to a colder new world.",
      "lat": -41.3,
      "lng": 174.8,
      "area": 1200
    },
    {
      "id": "mansa-musa",
      "title": "Mansa Musa's Pilgrimage to Mecca",
      "year": 1324,
      "category": "society",
      "continent": "africa",
      "emoji": "🐪",
      "who": "Mansa Musa, ruler of Mali",
      "where": "Mali to Mecca",
      "why": "Showed Mali's wealth; spread its fame.",
      "fact": "He travelled with a huge caravan and gave away so much gold that its value reportedly fell in Cairo for years.",
      "summary": "Mansa Musa ruled the wealthy West African empire of Mali. In 1324 he set out on the pilgrimage to Mecca with a huge caravan of soldiers, officials and camels loaded with gold. In Cairo he gave and spent so much gold that its value reportedly fell. Word of Mali's riches spread as far as Europe, and maps soon showed Mansa Musa holding a golden nugget.",
      "lat": 16.77,
      "lng": -3,
      "area": 1500
    },
    {
      "id": "tenochtitlan",
      "title": "Tenochtitlan Founded",
      "year": 1325,
      "circa": true,
      "category": "empire",
      "continent": "americas",
      "emoji": "🦅",
      "who": "The Mexica (Aztec) people",
      "where": "Lake Texcoco, Mexico",
      "why": "Capital of a powerful empire.",
      "fact": "On an island in a lake, the Mexica built causeways and floating gardens, and the city later held perhaps two hundred thousand people.",
      "summary": "According to Mexica tradition, their wandering people were guided to an island where they saw an eagle on a cactus. There, in 1325, they founded Tenochtitlan. In the middle of Lake Texcoco they built causeways, temples and floating gardens. The city grew into one of the largest in the world, the capital of the Aztec Empire.",
      "lat": 19.43,
      "lng": -99.13,
      "area": 100,
      "connections": [
        {
          "to": "columbus-landfall",
          "type": "contributing",
          "rationale": "Columbus's landfall begins the contact that ends Tenochtitlan; the city's wealth is what draws the Spanish inland."
        }
      ]
    },
    {
      "id": "black-death",
      "title": "Plague Reaches Europe at Messina",
      "year": 1347,
      "category": "society",
      "continent": "europe",
      "emoji": "☠️",
      "who": "Sailors and citizens of Messina",
      "where": "Messina, Sicily",
      "why": "The Black Death spread across Europe.",
      "fact": "Genoese ships carried the disease from the Black Sea, and within a few years it killed a large share of Europe's people.",
      "summary": "In 1347, ships returning to Messina in Sicily brought a deadly disease. It was probably plague, spread by fleas that lived on rats. The sickness swept along trade routes, and within a few years it killed roughly a third of Europe's people. The disaster shook the old order and changed wages, land and the way Europeans worked.",
      "lat": 38.19,
      "lng": 15.55,
      "area": 300,
      "connections": [
        {
          "to": "luther-theses",
          "type": "contributing",
          "rationale": "The plague's death toll weakened the feudal order and the church's standing, and the grievances the Reformation mobilises are the ones it left."
        }
      ]
    },
    {
      "id": "constantinople-falls",
      "title": "Constantinople Falls to the Ottomans",
      "year": 1453,
      "category": "war-peace",
      "continent": "middle-east",
      "emoji": "🛡️",
      "who": "Sultan Mehmed II; Emperor Constantine XI",
      "where": "Constantinople",
      "why": "Ended the Byzantine Empire.",
      "fact": "Massive cannon battered the walls, and the captured city became the Ottoman capital and a great centre of learning.",
      "summary": "Constantinople had been the capital of the Byzantine Empire for over a thousand years. In 1453, Sultan Mehmed II attacked it with a huge army and enormous cannon. The walls that had protected the city for centuries finally broke. Constantinople became the Ottoman capital. Many scholars fled west, carrying ancient Greek books that helped fuel the Renaissance.",
      "lat": 41.01,
      "lng": 28.98,
      "area": 200,
      "connections": [
        {
          "to": "columbus-landfall",
          "type": "contributing",
          "rationale": "With Constantinople in Ottoman hands the eastern trade ran through a rival, which made a sea route to Asia worth the risk - the argument Lisbon and Castile used."
        }
      ]
    },
    {
      "id": "columbus-landfall",
      "title": "Columbus Makes Landfall in the Americas",
      "year": 1492,
      "category": "exploration",
      "continent": "americas",
      "emoji": "⛵",
      "who": "Christopher Columbus and crew",
      "where": "Bahamas, Caribbean",
      "why": "Opened lasting contact between continents.",
      "fact": "He sailed west seeking Asia and reached islands where the Taíno people already lived, beginning an exchange of plants, animals and disease.",
      "summary": "Columbus sailed west from Spain in 1492 believing he could reach Asia. Instead he landed on islands in the Caribbean where the Taíno people already lived. His voyages began lasting contact between Europe and the Americas. The exchange of crops and animals changed diets worldwide, but European diseases and conquest devastated the peoples already there.",
      "lat": 24.25,
      "lng": -76,
      "area": 600,
      "connections": [
        {
          "to": "berlin-conference",
          "type": "contributing",
          "rationale": "The overseas empires that the Berlin Conference partitions are the ones Columbus's voyage opened."
        },
        {
          "to": "saint-domingue-uprising",
          "type": "contributing",
          "rationale": "Saint-Domingue is a colony built by the plantation economy the Columbian exchange created."
        }
      ]
    },
    {
      "id": "luther-theses",
      "title": "Luther Issues the Ninety-five Theses",
      "year": 1517,
      "category": "religion",
      "continent": "europe",
      "emoji": "⛪",
      "who": "Martin Luther",
      "where": "Wittenberg, Germany",
      "why": "Spark of the Protestant Reformation.",
      "fact": "He attacked the sale of indulgences, and cheap printing spread his challenge far beyond the university town.",
      "summary": "Martin Luther was a monk and teacher in Wittenberg who objected to the church selling indulgences. In 1517 he published ninety-five arguments against the practice. Cheap printing spread his words across Germany within weeks. Luther's challenge grew into the Protestant Reformation, which split western Christianity and reshaped European politics for centuries.",
      "lat": 51.87,
      "lng": 12.65,
      "area": 100
    },
    {
      "id": "babur-mughal",
      "title": "Babur Founds the Mughal Empire",
      "year": 1526,
      "category": "empire",
      "continent": "asia",
      "emoji": "🐘",
      "who": "Babur, a Central Asian prince",
      "where": "Panipat, northern India",
      "why": "Began a dynasty that ruled for centuries.",
      "fact": "His smaller army used gunpowder and field guns to defeat a far larger force, founding a dynasty that later raised the Taj Mahal.",
      "summary": "Babur was a Central Asian prince descended from both Genghis Khan and Tamerlane. Defeated in his homeland, he turned toward India. In 1526 he defeated a much larger army at Panipat using field artillery and gunpowder tactics. He founded the Mughal Empire, which eventually grew into one of the richest empires on earth.",
      "lat": 29.39,
      "lng": 76.97,
      "area": 1500,
      "connections": [
        {
          "to": "india-pakistan-independence",
          "type": "contributing",
          "rationale": "British India is the successor state to the Mughal empire; partition redraws the territory Babur founded."
        }
      ]
    },
    {
      "id": "american-revolution",
      "title": "American Revolution Begins at Lexington and Concord",
      "year": 1775,
      "category": "war-peace",
      "continent": "americas",
      "emoji": "🇺🇸",
      "who": "Colonial militia and British troops",
      "where": "Massachusetts",
      "why": "Started the war for American independence.",
      "fact": "A standoff over stored weapons turned into the first fighting, and militia harried the redcoats back to Boston.",
      "summary": "For years American colonists had argued with Britain over taxes and representation. In April 1775, British troops marched from Boston to seize stored weapons. At Lexington and Concord the first shots were fired. Colonial militias fought the redcoats back, and a war for independence had begun. It ended with the creation of the United States.",
      "lat": 42.45,
      "lng": -71.23,
      "area": 100,
      "connections": [
        {
          "to": "bastille",
          "type": "contributing",
          "rationale": "The French crown's debt from backing the American revolt is one of the fiscal crises that forced the calling of the Estates-General."
        }
      ]
    },
    {
      "id": "bastille",
      "title": "Storming of the Bastille",
      "year": 1789,
      "category": "governance",
      "continent": "europe",
      "emoji": "🇫🇷",
      "who": "Parisian crowd and soldiers",
      "where": "Paris, France",
      "why": "Symbolised the French Revolution's start.",
      "fact": "The crowd seized a royal fortress to find gunpowder, and the gloomy prison held only a few prisoners that day.",
      "summary": "By 1789 France was deep in debt and its people were angry. On 14 July a Paris crowd stormed the Bastille, a royal fortress and prison, looking for gunpowder. Only a few prisoners were freed, but the fall of the fortress became a symbol that ordinary people could challenge a king. The French Revolution had begun.",
      "lat": 48.85,
      "lng": 2.35,
      "area": 60,
      "connections": [
        {
          "to": "saint-domingue-uprising",
          "type": "contributing",
          "rationale": "Saint-Domingue's free people of colour and its enslaved majority took the Rights of Man at their word, and the revolution in France made the colony's order negotiable."
        }
      ]
    },
    {
      "id": "saint-domingue-uprising",
      "title": "Slave Uprising Begins in Saint-Domingue",
      "year": 1791,
      "category": "governance",
      "continent": "americas",
      "emoji": "✊",
      "who": "Enslaved Africans and their leaders",
      "where": "Saint-Domingue (Haiti)",
      "why": "Led to the first free Black republic.",
      "fact": "Enslaved workers rose against their enslavers and, after years of struggle, won the first Black republic in the Americas.",
      "summary": "Saint-Domingue was France's richest colony, worked by huge numbers of enslaved Africans. In 1791 they rose in revolt against their enslavers. Led by figures such as Toussaint Louverture, the rebels fought a long and brutal war. In 1804 they won independence as Haiti, the first Black republic in the Americas and the only nation born of a successful uprising of enslaved people.",
      "lat": 18.54,
      "lng": -72.34,
      "area": 300,
      "connections": [
        {
          "to": "us-civil-war-first",
          "type": "contributing",
          "rationale": "Haiti's revolution is proof that enslaved people could win, and the fear it produced shaped the politics of slavery in the United States."
        }
      ]
    },
    {
      "id": "us-civil-war-first",
      "title": "US Civil War Begins at Fort Sumter",
      "year": 1861,
      "category": "war-peace",
      "continent": "americas",
      "emoji": "🎖️",
      "who": "Union and Confederate forces",
      "where": "Charleston, South Carolina",
      "why": "Deadliest war in American history.",
      "fact": "Guns fired on a federal fort in the harbour, and the war that followed ended slavery but killed more Americans than any other.",
      "summary": "America was divided over slavery. When Abraham Lincoln was elected president, southern states left the Union. In April 1861, Confederate forces fired on Fort Sumter in Charleston harbour. The war that followed lasted four years and killed more Americans than any other conflict. It ended slavery, and the former enslaved people were freed but faced a long struggle for equality.",
      "lat": 32.75,
      "lng": -79.87,
      "area": 100,
      "connections": [
        {
          "to": "human-rights-declaration",
          "type": "contributing",
          "rationale": "The Thirteenth to Fifteenth Amendments begin the constitutional arc that the Declaration later states as universal rights."
        }
      ]
    },
    {
      "id": "meiji-restoration",
      "title": "Meiji Restoration Proclaimed",
      "year": 1868,
      "category": "governance",
      "continent": "asia",
      "emoji": "🎌",
      "who": "Emperor Meiji and reformers",
      "where": "Japan",
      "why": "Rapid modernisation of Japan.",
      "fact": "Young Japanese reformers returned power to the emperor and set out to industrialise the country within a single generation.",
      "summary": "Japan had been ruled by shoguns for centuries and kept mostly closed to the outside world. In 1868 a group of reformers restored the emperor to power and promised sweeping change. The new government built railways and factories, created a modern army and reformed schools. Within a generation, Japan had become an industrial and military power.",
      "lat": 35.01,
      "lng": 135.77,
      "area": 800,
      "connections": [
        {
          "to": "ww1-first",
          "type": "contributing",
          "rationale": "A restored, industrialising Japan joins the great-power system and enters the First World War on the Allied side."
        },
        {
          "to": "ww2-first",
          "type": "contributing",
          "rationale": "The industrial-military state Meiji built is the one that later expands into Asia and joins the Axis."
        }
      ]
    },
    {
      "id": "berlin-conference",
      "title": "Berlin Conference Sets Rules for Africa's Partition",
      "year": 1884,
      "yearEnd": 1885,
      "category": "governance",
      "continent": "africa",
      "emoji": "🗺️",
      "who": "European powers",
      "where": "Berlin, Germany",
      "why": "Divided Africa among colonisers.",
      "fact": "No African rulers took part, yet the delegates drew borders that split communities and ignored existing kingdoms.",
      "summary": "European countries had begun racing to claim territory in Africa. In 1884, leaders met in Berlin to agree on rules for the scramble. No African rulers were invited. The delegates drew borders across the continent, ignoring existing kingdoms and communities. Those lines divided peoples and set the stage for conflicts that lasted long after independence.",
      "lat": 52.52,
      "lng": 13.4,
      "area": 200,
      "connections": [
        {
          "to": "ww1-first",
          "type": "contributing",
          "rationale": "The rival colonial claims the conference regulated became a source of great-power friction in 1914."
        },
        {
          "to": "ghana-independence",
          "type": "contributing",
          "rationale": "Independence movements in Africa set out to undo the partition the conference drew."
        }
      ]
    },
    {
      "id": "ww1-first",
      "title": "World War I Begins",
      "year": 1914,
      "category": "war-peace",
      "continent": "europe",
      "emoji": "💥",
      "who": "Allied and Central Powers",
      "where": "Europe, then the world",
      "why": "A global war that reshaped empires.",
      "fact": "An assassin's bullets in Sarajevo set off a chain of alliances that pulled a continent into four years of trench slaughter.",
      "summary": "By 1914 Europe was divided into two armed camps. When a young assassin shot an archduke in Sarajevo, alliances pulled one country after another into war. The fighting lasted four years and used tanks, planes and poison gas for the first time on a huge scale. Empires collapsed, and around seventeen million people died. The peace that followed helped cause another war.",
      "lat": 50,
      "lng": 10,
      "area": "world",
      "connections": [
        {
          "to": "ww2-first",
          "type": "contributing",
          "rationale": "The settlement of 1919 and the grievances it left unresolved are the ground of the second war."
        }
      ]
    },
    {
      "id": "ww2-first",
      "title": "World War II Begins in Europe",
      "year": 1939,
      "category": "war-peace",
      "continent": "europe",
      "emoji": "💣",
      "who": "Axis and Allied powers",
      "where": "Europe, then worldwide",
      "why": "The deadliest conflict in history.",
      "fact": "German forces invaded Poland, and the war that followed spread across continents and killed tens of millions of civilians and soldiers.",
      "summary": "World War II began when German forces invaded Poland in 1939. It became the deadliest conflict in history, fought across Europe, Asia, Africa and the oceans. Around six million Jewish people were murdered in the Holocaust, along with millions of others. The war ended in 1945 after the first atomic bombs. It changed the map of the world and led to the United Nations.",
      "lat": 52,
      "lng": 20,
      "area": "world",
      "connections": [
        {
          "to": "united-nations",
          "type": "contributing",
          "rationale": "The United Nations is created by the wartime alliance specifically so that there is no third; the charter is signed by the victors."
        },
        {
          "to": "human-rights-declaration",
          "type": "contributing",
          "rationale": "The atrocities of the war are the direct occasion for the Declaration."
        }
      ]
    },
    {
      "id": "united-nations",
      "title": "United Nations Founded",
      "year": 1945,
      "category": "governance",
      "continent": "global",
      "emoji": "🌐",
      "who": "Fifty-one founding nations",
      "where": "San Francisco, USA",
      "why": "Aims to keep world peace and protect rights.",
      "fact": "Delegates signed a charter in San Francisco, creating a council of great powers with a veto over its decisions.",
      "summary": "After two devastating world wars, many countries wanted a body that could help keep the peace. In 1945 delegates met in San Francisco and signed the charter of the United Nations. The new organisation had a General Assembly where every member had a voice. A Security Council of great powers could pass binding decisions — and each of its five members could block them with a veto.",
      "lat": 37.77,
      "lng": -122.42,
      "area": 200,
      "connections": [
        {
          "to": "human-rights-declaration",
          "type": "necessary",
          "rationale": "The Declaration is drafted and adopted by the UN Commission on Human Rights; the body is the instrument."
        }
      ]
    },
    {
      "id": "india-pakistan-independence",
      "title": "India and Pakistan Gain Independence",
      "year": 1947,
      "category": "governance",
      "continent": "asia",
      "emoji": "🇮🇳",
      "who": "Indian independence leaders",
      "where": "South Asia",
      "why": "Ended British rule; created two states.",
      "fact": "Freedom came with partition, and the new British-drawn borders set off mass migration and deadly violence between communities.",
      "summary": "After years of protest and struggle, Britain agreed to give India independence in 1947. The country was divided into two new states: Hindu-majority India and Muslim-majority Pakistan. Millions of people moved across the new borders in one of the largest migrations in history. The partition brought terrible violence, and its effects are still felt today.",
      "lat": 28.61,
      "lng": 77.21,
      "area": 1000,
      "connections": [
        {
          "to": "mandela-president",
          "type": "contributing",
          "rationale": "India's independence is the model and the morale for the decolonisation that follows."
        }
      ]
    },
    {
      "id": "human-rights-declaration",
      "title": "Universal Declaration of Human Rights Adopted",
      "year": 1948,
      "category": "governance",
      "continent": "global",
      "emoji": "⚖️",
      "who": "United Nations delegates",
      "where": "Paris, France",
      "why": "First global statement of human rights.",
      "fact": "Drafted after the horrors of war, it set out thirty articles covering freedom, fairness and dignity for every person.",
      "summary": "After the horrors of World War II, nations wanted to agree on the basic rights that every person should have. In 1948 the United Nations adopted the Universal Declaration of Human Rights. Its thirty articles say that all people are born free and equal, and deserve freedom of thought, fair trials and education. It is now the most translated document in the world.",
      "lat": 48.85,
      "lng": 2.35,
      "area": 200,
      "connections": [
        {
          "to": "mandela-president",
          "type": "contributing",
          "rationale": "The Declaration's language of equal rights is cited in the struggle against apartheid."
        }
      ]
    },
    {
      "id": "ghana-independence",
      "title": "Ghana Gains Independence",
      "year": 1957,
      "category": "governance",
      "continent": "africa",
      "emoji": "🇬🇭",
      "who": "Kwame Nkrumah and Ghanaians",
      "where": "Ghana, West Africa",
      "why": "First sub-Saharan colony to gain freedom.",
      "fact": "It became the first colony in sub-Saharan Africa to win independence, inspiring freedom movements across the continent.",
      "summary": "In 1957 Ghana became the first country in sub-Saharan Africa to win independence from European colonial rule. Its leader, Kwame Nkrumah, had organised peaceful protests and strikes for years. Ghana's success inspired people across the continent. Within a decade, most African colonies had won their freedom. Nkrumah later became president and helped found the Organisation of African Unity.",
      "lat": 5.56,
      "lng": -0.2,
      "area": 500,
      "connections": [
        {
          "to": "mandela-president",
          "type": "contributing",
          "rationale": "Ghana is the first sub-Saharan colony to win independence, and it became a base and an emblem for the African liberation movements."
        }
      ]
    },
    {
      "id": "berlin-wall-falls",
      "title": "Berlin Wall Falls",
      "year": 1989,
      "category": "war-peace",
      "continent": "europe",
      "emoji": "🧱",
      "who": "East and West Berliners",
      "where": "Berlin, Germany",
      "why": "Symbolised the end of the Cold War.",
      "fact": "Crowds crossed the checkpoints, chipping at the concrete with hammers, and Germany reunited within a year.",
      "summary": "The Berlin Wall was built in 1961 to stop people escaping from communist East Berlin to the west. For years it cut a city in two. In 1989, peaceful protests and loosening Soviet control led crowds to gather at the crossings. Guards let them through, and people began chipping at the wall with hammers. Within a year Germany was reunited.",
      "lat": 52.52,
      "lng": 13.4,
      "area": 100,
      "connections": [
        {
          "to": "mandela-president",
          "type": "contributing",
          "rationale": "The end of the Cold War removes the superpower rivalry that had propped up apartheid's sponsors."
        }
      ]
    },
    {
      "id": "mandela-president",
      "title": "Mandela Becomes President of South Africa",
      "year": 1994,
      "category": "governance",
      "continent": "africa",
      "emoji": "🇿🇦",
      "who": "Nelson Mandela and the ANC",
      "where": "Pretoria, South Africa",
      "why": "First democratic election in South Africa.",
      "fact": "After years in prison, he led a party that won the country's first election open to all races, ending white-minority rule.",
      "summary": "Nelson Mandela spent twenty-seven years in prison for fighting apartheid, South Africa's system of racial segregation. Released in 1990, he helped negotiate an end to white-minority rule. In 1994 South Africans of every race voted in a free election for the first time, and Mandela became president. He later became a global symbol of forgiveness and reconciliation.",
      "lat": -25.75,
      "lng": 28.19,
      "area": 800
    }
  ],
  "narration": {
    "engine": "kokoro",
    "model": "onnx-community/Kokoro-82M-v1.0-ONNX",
    "dtype": "fp32",
    "voice": "af_heart",
    "sampleRate": 24000,
    "format": "mp3",
    "bitrateKbps": 64,
    "textRule": "strip-years-v2",
    "loudnessLufs": -16,
    "generated": "2026-09-30",
    "files": {
      "alexander-dies": {
        "path": "decks/world-history-first-timeline/narration/alexander-dies.mp3",
        "bytes": 68948,
        "sha256": "a6165c88270f48749f23019d02a65e07e020984c8d54cb638d32dd42fcf4e832",
        "textHash": "aed1d1384323c2992058e83957c53d33e17b978c58c43743efd31de7fe3a1a13",
        "durationMs": 8616
      },
      "athenian-democracy": {
        "path": "decks/world-history-first-timeline/narration/athenian-democracy.mp3",
        "bytes": 82964,
        "sha256": "d1b4d0120b956fb06c707b45c90bed4e28f5d311b49f3e1ec9439cf2055d8e7a",
        "textHash": "f1e7c1db208032aecdfcdaa0bab12a4a099ebf4cf927ee6a354ca67fa1b20e6a",
        "durationMs": 10368
      },
      "augustus-principate": {
        "path": "decks/world-history-first-timeline/narration/augustus-principate.mp3",
        "bytes": 79700,
        "sha256": "7234ae08453b5070d920401b01709d6f609258d02a32f3f7d38833a1a67e0080",
        "textHash": "f38dcf640e9e595d5ef474f05e0824ea44dc0f79efa74e6d569673faaf305a7d",
        "durationMs": 9960
      },
      "birth-of-jesus": {
        "path": "decks/world-history-first-timeline/narration/birth-of-jesus.mp3",
        "bytes": 52244,
        "sha256": "f461f07538cd235ec93251a17be958434c07c28ce1daa13706daba0f8d60d696",
        "textHash": "20e843f25c6df0ed12373434dbc8c0d8ecb502a686d302bdebd0642e05fc11b8",
        "durationMs": 6528
      },
      "buddha-monastic-order": {
        "path": "decks/world-history-first-timeline/narration/buddha-monastic-order.mp3",
        "bytes": 78740,
        "sha256": "2759cffe2a1ec306b150dd6951b7b8987e1484d4eff639afb8282d7cf416632a",
        "textHash": "ad0653025c56d469558cd6157ad1acae41c3292d2a95b3dbb8dbc7daedd6d72a",
        "durationMs": 9840
      },
      "confucius": {
        "path": "decks/world-history-first-timeline/narration/confucius.mp3",
        "bytes": 66260,
        "sha256": "a232ecc0265e9e3b32b351dc242c0c181fb09ecb6b997b36e9a30e3b9b495353",
        "textHash": "b73dcaece28a91044a1b1c6d59665df88c472770bfaab3fcfaa6aa509ed0eca6",
        "durationMs": 8280
      },
      "egypt-unifies": {
        "path": "decks/world-history-first-timeline/narration/egypt-unifies.mp3",
        "bytes": 61844,
        "sha256": "67d86e4feed5910158cf77434a15a6c7a3fc6a20a78bde091e3f6844e9856fea",
        "textHash": "1388742602ab865aa90dd6236015592a2ef738617a169a804d272f18db35476c",
        "durationMs": 7728
      },
      "great-pyramid": {
        "path": "decks/world-history-first-timeline/narration/great-pyramid.mp3",
        "bytes": 64724,
        "sha256": "d4e571fbbe4e43ab29d791afb1fcbca24aca6649b83854a13bdf914e2e4d6f26",
        "textHash": "471065e1a6393c661c1f82c098427141b857e5932cfe29072be13255a07d1e4e",
        "durationMs": 8088
      },
      "plato-academy": {
        "path": "decks/world-history-first-timeline/narration/plato-academy.mp3",
        "bytes": 69524,
        "sha256": "b477b5ed75711ac15cad8fd4a0230c45659cade7a6dbb15c5015909e5c1cdaba",
        "textHash": "af676f8b95e89255e69cd3c028f5bb78e732d8d314e224929793363ea0ac889a",
        "durationMs": 8688
      },
      "qin-unifies-china": {
        "path": "decks/world-history-first-timeline/narration/qin-unifies-china.mp3",
        "bytes": 65300,
        "sha256": "7c189c6c94983590f09c8e699bef3c34e1a0a34d5c2106111a5861d186fff0a2",
        "textHash": "694124c4785ea233fa710c029c7af48bf62314fe785bd490eebac62a9fc04f31",
        "durationMs": 8160
      },
      "first-peoples-australia": {
        "path": "decks/world-history-first-timeline/narration/first-peoples-australia.mp3",
        "bytes": 58388,
        "sha256": "88d1d02987023f566300ff8c5f31ec35c00ad21ada7f626e0460602540b4031d",
        "textHash": "47c697cb186b7b82da89f0ef251906172457956b4cb49ab0994ada49cae04238",
        "durationMs": 7296
      },
      "first-farming": {
        "path": "decks/world-history-first-timeline/narration/first-farming.mp3",
        "bytes": 56276,
        "sha256": "4c9d8744f731ccadf000434a18efb3c375f87ec1ec71dc8977bab7acdec1bdaf",
        "textHash": "835392e28728aee3f5771ae689dc93d20d58bad20ebb96c3e1b76613fc356144",
        "durationMs": 7032
      },
      "fall-western-rome": {
        "path": "decks/world-history-first-timeline/narration/fall-western-rome.mp3",
        "bytes": 86420,
        "sha256": "625cece15a3f7e099b7b421ce13bf54e421022d8ccaac97e48c878fd230badeb",
        "textHash": "402a8d026e91a42d357e6e783bfa099e1aa12b4d920f3f29ede1b603122fd732",
        "durationMs": 10800
      },
      "hijra": {
        "path": "decks/world-history-first-timeline/narration/hijra.mp3",
        "bytes": 75860,
        "sha256": "a5ce513ce81a92deef47b637fbced33577203b7b634ee1816aae02aed30958f6",
        "textHash": "cc7e215416c4b9c888ddac55dac4991fd19f5d9438b9fe1940e0a6699ff689f1",
        "durationMs": 9480
      },
      "charlemagne": {
        "path": "decks/world-history-first-timeline/narration/charlemagne.mp3",
        "bytes": 61460,
        "sha256": "8af930279443d48b864ed0136de86458010ba00d0e346ac7556c51803f5c328b",
        "textHash": "26810b826e103e7ebd8034eaf47e4bc5aab3a9a6c914a8706874cd188144554a",
        "durationMs": 7680
      },
      "battle-hastings": {
        "path": "decks/world-history-first-timeline/narration/battle-hastings.mp3",
        "bytes": 54932,
        "sha256": "17b270938030d61315c13559e47e4db12797f5071340151cdd7226fb5286589c",
        "textHash": "ff57cc3a5ffa90e1692e609ccc71e31b2d9726b815218707f161618d93b76897",
        "durationMs": 6864
      },
      "genghis-khan": {
        "path": "decks/world-history-first-timeline/narration/genghis-khan.mp3",
        "bytes": 72020,
        "sha256": "b8857b9bb2f56bb50bf1ff1c6b1059da3e8115aaff16ea30fb8f566629314121",
        "textHash": "062cac1134d23bdef83d3202231cbe7f83dfc2e06c69c9d5a5d27f5cf027798a",
        "durationMs": 9000
      },
      "magna-carta-first": {
        "path": "decks/world-history-first-timeline/narration/magna-carta-first.mp3",
        "bytes": 66260,
        "sha256": "6da8730678b845a33ce52ceef1a168f59374ba8835aac47545f2d39cc8b23717",
        "textHash": "6ffd48a3c768c5fc40a979693c0a472788455fea0a1be217ea89f1dd6b5b6300",
        "durationMs": 8280
      },
      "polynesians-aotearoa": {
        "path": "decks/world-history-first-timeline/narration/polynesians-aotearoa.mp3",
        "bytes": 77588,
        "sha256": "ddf16fc47ced8b925134e62a9f1bfec7afc0027f361f0333f586cf5333112c3d",
        "textHash": "fea9fe0c3b43877bad1e65b661a8bd44e7f1dcec90698d4249d988b3fd76516d",
        "durationMs": 9696
      },
      "mansa-musa": {
        "path": "decks/world-history-first-timeline/narration/mansa-musa.mp3",
        "bytes": 72404,
        "sha256": "7f86788c30815608e2e09c770ac254c598d208a6a5eaff68c58032dff46b3dea",
        "textHash": "89f0068c80ac45003df80122e5734d46512974b653321dec51ddba5c4547a3bc",
        "durationMs": 9048
      },
      "tenochtitlan": {
        "path": "decks/world-history-first-timeline/narration/tenochtitlan.mp3",
        "bytes": 71828,
        "sha256": "f26e7f1d78fe137d42dafa26260421dcf20bb5f188c90ad317581c6f57c42dfc",
        "textHash": "6aa2006d4389637f5568916daaa793ae8a587904130cf81a9be4cb4b74e614dd",
        "durationMs": 8976
      },
      "black-death": {
        "path": "decks/world-history-first-timeline/narration/black-death.mp3",
        "bytes": 65492,
        "sha256": "12f61c5070174ac19cc56235358d9845980b7f2be9641c2a2e3a0aead55ae8e0",
        "textHash": "f989130912d615265ec0e2caad832264de827f0a765b2940fd2b7efbb1c273de",
        "durationMs": 8184
      },
      "constantinople-falls": {
        "path": "decks/world-history-first-timeline/narration/constantinople-falls.mp3",
        "bytes": 69716,
        "sha256": "e66c3c0135331fe789ed07a89d3f3a67ee6d0098b39ef8310a8e11b6e2c8d7d8",
        "textHash": "b042775b6b96f49c1884ad42ed1b12545cfcd1a109255645a45349716de80d54",
        "durationMs": 8712
      },
      "columbus-landfall": {
        "path": "decks/world-history-first-timeline/narration/columbus-landfall.mp3",
        "bytes": 85844,
        "sha256": "1f53270c2a49bc929ca48bf7565a8d956ef994a34d4cd94f79f75d3994a7d0aa",
        "textHash": "ddfa487ca108c2f43f0f98e0afe8491c75c7113bbc4a80ba13c35871538fe444",
        "durationMs": 10728
      },
      "luther-theses": {
        "path": "decks/world-history-first-timeline/narration/luther-theses.mp3",
        "bytes": 70100,
        "sha256": "11cb6930d477b3764e3a1cf77a590db6f7fc93a568254afc67d0fe5e0a5d3087",
        "textHash": "587c2feba141e57710ec28f7f41093e20b5d3c20f1d7e30f340188a73216f05c",
        "durationMs": 8760
      },
      "babur-mughal": {
        "path": "decks/world-history-first-timeline/narration/babur-mughal.mp3",
        "bytes": 84500,
        "sha256": "ef8b87d5219d1eb67b9e62e5347fd388ad0af42318e9afd0f1aa74c194cff288",
        "textHash": "be4c5d569b611f74e412c8784e60f250c27f035936f01793176fedc58c6fd3fe",
        "durationMs": 10560
      },
      "american-revolution": {
        "path": "decks/world-history-first-timeline/narration/american-revolution.mp3",
        "bytes": 76628,
        "sha256": "89604745510c07b894061b48a54c7679fecf1fcfa4862c0959a1645e3439fde1",
        "textHash": "8e43d4104d6964073b9000ea9c9c3a639d8c92d8ccaba9141d217590182abbcc",
        "durationMs": 9576
      },
      "bastille": {
        "path": "decks/world-history-first-timeline/narration/bastille.mp3",
        "bytes": 62228,
        "sha256": "c1f70a1fe98a6c62f047ffa72ef78e581def84c81d4c47cffa35c36382035552",
        "textHash": "491ff34fa1cf6917ce6262f094d989dc7d5c3e065064922f731961d100422343",
        "durationMs": 7776
      },
      "saint-domingue-uprising": {
        "path": "decks/world-history-first-timeline/narration/saint-domingue-uprising.mp3",
        "bytes": 80660,
        "sha256": "24bae991cdf59c95ae1701926ea35a4ce870baaccc29314cd802c762af67bbda",
        "textHash": "1134085da895f01ab37ee4f172b55723ff1068ed1ea93f932b9544a113f71d57",
        "durationMs": 10080
      },
      "us-civil-war-first": {
        "path": "decks/world-history-first-timeline/narration/us-civil-war-first.mp3",
        "bytes": 76628,
        "sha256": "a17a7a839411057d31cedf6a229b680f83ceadf744bb3f37b180faff1fed1db2",
        "textHash": "4ee4eb18731a6312c0d3d569b909de2381d47918f8da78064aaa3b250591ed81",
        "durationMs": 9576
      },
      "meiji-restoration": {
        "path": "decks/world-history-first-timeline/narration/meiji-restoration.mp3",
        "bytes": 73748,
        "sha256": "d5a9af1c3ac582fab258bba2690085f9878adc7785e33fc484556e752b0ca2d3",
        "textHash": "17994eea55c416ebea29b866e26e8e8587509ad38c065353a68c25a1e42d2e61",
        "durationMs": 9216
      },
      "berlin-conference": {
        "path": "decks/world-history-first-timeline/narration/berlin-conference.mp3",
        "bytes": 79700,
        "sha256": "a079ebb1cc9a67de5fe782448c0a8e59f437311142507477c222c576459eaf1c",
        "textHash": "3a24c6f6133fa5fcd99835d20d5902610121f621b971191eb28542493a17e478",
        "durationMs": 9960
      },
      "ww1-first": {
        "path": "decks/world-history-first-timeline/narration/ww1-first.mp3",
        "bytes": 70484,
        "sha256": "587bc5500fab8a0513cb6cb6127cf33dc45d6806e394561fc315dbfc4e10a32b",
        "textHash": "9d8a7048bcd9db3c6467fb677eec4e34616943832e944bf0ca1b0c3643e8e52c",
        "durationMs": 8808
      },
      "ww2-first": {
        "path": "decks/world-history-first-timeline/narration/ww2-first.mp3",
        "bytes": 80660,
        "sha256": "1e7913fe6aa3414e56689a15e67f2094d620cce438aa43383a7d62dc47a81502",
        "textHash": "ba14dfea0baaad57e052ba2f04609ac06f9342a8ecdb74829d6b1609ca703ab6",
        "durationMs": 10080
      },
      "united-nations": {
        "path": "decks/world-history-first-timeline/narration/united-nations.mp3",
        "bytes": 66644,
        "sha256": "c194758cafc8e677e29d4bd0d0f6e3ee8530a3bc0a783fa3254e51d7b9fbec25",
        "textHash": "8072338b7a56040a0e3a3abbe885893eb5716ba0d5d964055fc093f8cdaabbc5",
        "durationMs": 8328
      },
      "india-pakistan-independence": {
        "path": "decks/world-history-first-timeline/narration/india-pakistan-independence.mp3",
        "bytes": 79508,
        "sha256": "9d4e7a418eeffdc3cfe46355cddd5fa17a468fa38f8ef57e2f4dc5df0801b0fe",
        "textHash": "9863943a1c54827570393f24a0d4e5f05787d1b7fbb54ac35195b644484e582d",
        "durationMs": 9936
      },
      "human-rights-declaration": {
        "path": "decks/world-history-first-timeline/narration/human-rights-declaration.mp3",
        "bytes": 79124,
        "sha256": "aa1ab7a37fdf3b757aef00b8de8dca52b9f061cdc06a6490a9bc6605d026cf70",
        "textHash": "a4ad18ac7f72e3456831cd323ff590afbc334b3041618c6409995cdb63887b95",
        "durationMs": 9888
      },
      "ghana-independence": {
        "path": "decks/world-history-first-timeline/narration/ghana-independence.mp3",
        "bytes": 73556,
        "sha256": "495fb503827831540cb29fc01b5e490d3a9ae2b8f18beda0b2901be422932d22",
        "textHash": "4479c19df40e1bb5d62a350ad53c5b4fb224a49f63627db1a6cb4cded280baca",
        "durationMs": 9192
      },
      "berlin-wall-falls": {
        "path": "decks/world-history-first-timeline/narration/berlin-wall-falls.mp3",
        "bytes": 55892,
        "sha256": "58e4533a2b014f28c2bc036a3a91d6745d2a3eef2bf6fd8db789c783c61863b9",
        "textHash": "161f1cc98e860d29c175cff5e25ac1609234de79268a10a09f894ec04fdc5ecb",
        "durationMs": 6984
      },
      "mandela-president": {
        "path": "decks/world-history-first-timeline/narration/mandela-president.mp3",
        "bytes": 79124,
        "sha256": "a301a3ee6e7e7234e828fe0b795188acdb040dd4747c2c801f4e8548a65b381d",
        "textHash": "a9ec41b6bc3c8bcf0d0f42606c0cee2878f7cee48ce7f6b5fc644d18a44ea3cb",
        "durationMs": 9888
      }
    }
  },
  "version": "1.0.0",
  "license": "CC-BY-SA-4.0",
  "attribution": []
});
