/* GENERATED by scripts/gen-deck-manifest.mjs — do not edit by hand. */
window.DECK_MANIFEST = {
  "schemaVersion": 2,
  "decks": [
    {
      "file": "classical-conversations.js",
      "revision": "f3ca0cb1458a",
      "bytes": 61406,
      "grandfathered": true
    },
    {
      "file": "inventions-discoveries.js",
      "revision": "41b6318287d3",
      "bytes": 38329
    },
    {
      "file": "world-history-first.js",
      "revision": "60d2c07bb0ba",
      "bytes": 36704
    },
    {
      "file": "world-literature.js",
      "revision": "0ab38fad71ae",
      "bytes": 46920,
      "grandfathered": true
    }
  ]
};
